### ISSUE TITLE
Support CLI usage

### ISSUE THREAD

**Issue by MattiSG** [natesilva/jayschema#48]
I would like to just `$ jayschema my-schema.json`  :)

**Comment by natesilva** [comment]
You actually can do this! First, install globally:

    [sudo] npm install -g jayschema

Then you will have a command-line utility:

```
$ jayschema 
Syntax: jayschema <instance> [<schema>]
	if <schema> is omitted, the <instance> will be validated
	against the JSON Schema Draft v4 meta-schema
```
