### ISSUE TITLE
Validating schemas themselves

### ISSUE THREAD

**Issue by adamsch1** [natesilva/jayschema#50]
Howdy,

This is a really great library, thank you.

I am puzzled why jayschema would accept [I've tested a few other validators as well] 

 var res = js.validate( {},  { "dtype": "integer", "multipleOf": 8 } );

Note dtype which isn't part of the spec, yet this test passes.  I must be missing something obvious.  I would expect the schema to be checked if invalid.

**Comment by ghartsho** [comment]
I handled this by validating all my schema against the schema schema listed here
http://json-schema.org/shared.html

**Comment by adamsch1** [comment]
Thanks Ghartsho,  you mean you validated it manually?  I was trying to do this at runtime with un-vetted schemas.

**Comment by adamsch1** [comment]
Oh never mind.  I see there is a schema for schemas :)  Thanks!
